on:
  push:
    branches:
      - main # main ブランチへの Push 時にワークフローを実行
jobs:
  connect_ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
       key: ${{ secrets.SECRET_KEY }}
       name: id_rsa # optional
       known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
       config: ${{ secrets.CONFIG }} # ssh_config; optional
       if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - name: run script
      run: ssh target "cd /home/${user}/youmu_bot && git pull origin main"
