on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Passwd
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY }} # 必須
        name: id_rsa
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # 省略可
    - name: run deploy script
      env:
        port: ${{ secrets.PORT }}
        host: ${{ secrets.HOST }}
        owner:  ${{ secrets.OWNER }}
      run:
        ssh -i ~/.ssh/id_rsa -p ${port} ${owner}@${host} "cd /home/${owner}/youmu_bot && git pull origin main"
