on:
  push:
    branches:
      - maine
jobs:
  connect_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.SECRET_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}
      - name: Connect SSH
        run: ssh target echo "test"
