on:
  push:
    branches:
      - main # main ブランチへの Push 時にワークフローを実行
jobs:
  connect_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SECRET_KEY }} # サーバへの接続情報は secrets へ保持するようにしています
          name: id_rsa-target
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}
          if_key_exists: fail
      - name: Connect SSH
        run: ssh target echo "test"
