on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Passwd
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SECRET_KEY }} # 必須
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # 省略可
    - name: run deploy script
      env:
        port: ${{ secrets.PORT }}
        host: ${{ secrets.HOST }}
        user:  ${{ secrets.USER }}
      run:
        ssh -p ${port} ${user}@${host} "cd /home/${user}/youmu_bot && git pull origin main"
