on:
  push:
    branches:
      - main
name: Auto Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_KEY }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.CONFIG }}
    - name: run deploy script
      run:
        ssh target "cd /home/${owner}/youmu_bot && git pull origin main && sudo python3 restart.py"
